---
title: A Biblical Response
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: /:categories/:title:output_ext
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
author: Admin
description: Welcome!
